server:
  port: 8083


spring:
  application:
    name: gestion-compte-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gestion-compte?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Ilyas.00
    hikari:
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
