server:
  port: 8090


spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: dossier-medical-service
          predicates:
            - Path=/dossier-medical-service/**
          filters:
            - RewritePath=/dossier-medical-service/(?<s>.*), /${s}
          uri: lb://dossier-medical-service

        - id: examen-clinique-service
          predicates:
            - Path=/examen-clinique-service/**
          filters:
            - RewritePath=/examen-clinique-service/(?<s>.*), /${s}
          uri: lb://examen-clinique-service


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://localhost:8761/eureka/

  instance:
    hostname: localhost

